### PR TITLE
Update to latest upstream hubot-slack

### PR DESCRIPTION
**Pull request by mistydemeo**
This'll allow is to get to the latest `@slack/client`, which will be necessary for us to be able to upgrade the node used by our hubot.

It looks like we only had a couple substantive points of divergeance at this point - our other changes got adapted upstream, even if they were in somewhat different forms. Most of this is just a merge commit, with the main changes being commits 16c261337b46501096783da2c17f4e232c69bf09 and c353581490a8ff13b25e807d6b1293680d10ddf5, which cover a) truncating messages, and b) sending messages as attachments instead of text.

### CODE REVIEW

**Comment by bhuga** [comment]
:clap: I never thought this possible. Not going to attempt to get through the diff, but one question:

>  a) truncating messages

In chatops RPC we now auto-snippet very long messages. Should we promote that to the default behavior?

**Comment by bhuga** [comment]
> Maybe in a followup PR?

Yeah good call. This is drastic enough as it is.

**Comment by mistydemeo** [comment]
> https://twitter.com/goliath_otter/status/841623872654921728

I kept changes out of the merge, so it's worth looking at the last two commits which port our behaviour back. The code surrounding those parts hasn't changed *too* drastically.

**Comment by mistydemeo** [comment]
Lol, that was a great paste fail. Enjoy your wallaby photo if you can still see it.

**Comment by bhuga** [comment]
> Lol, that was a great paste fail. Enjoy your wallaby photo if you can still see it.

More wallabies and otters please.

> I kept changes out of the merge, so it's worth looking at the last two commits which port our behaviour back. 

I did look at these and am :+1: on them. Sorry I didn't circle back to the main diff to click 'approve'.

**Comment by technicalpickles** [comment]
> I kept changes out of the merge, so it's worth looking at the last two commits which port our behaviour back. The code surrounding those parts hasn't changed too drastically.

Would it be possible to move those to a PR upstream? Would make it a lot easier to review what's left that is different.

**Comment by mistydemeo** [comment]
> Would it be possible to move those to a PR upstream?

It all has to do with sending everything as an attachment, which is behaviour specific to our installation; I'm not sure if that's something upstream would be interested in.

**Pull request merged**
